"""Generate deterministic data and images for the static architecture atlas."""
from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from dataclasses import fields, is_dataclass
from enum import Enum
import hashlib
from html import escape
import json
from pathlib import Path
import re
import shutil
import sys
import tempfile
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scenes import scene_dict  # noqa: E402
from restir_lab.debug import PixelSelection, replay_pixel  # noqa: E402
from restir_lab.debug.pipeline_records import pipeline_replay  # noqa: E402
from restir_lab.debug.view3d import (debug_bounds, image_plane,  # noqa: E402
                                     scene_wireframe)
from restir_lab.l0_scene import load_edn, lower_scene  # noqa: E402
from restir_lab.l1_graph import (compile_pipeline,  # noqa: E402
                                 pipeline_from_integrator)
from restir_lab.l1_graph.operators import builtin_operator_catalog  # noqa: E402
from restir_lab.l2_kernels.path import (IntegratorConfig,  # noqa: E402
                                        PathEstimatorConfig)
from restir_lab.l3_backend import scalar  # noqa: E402
from restir_lab.l3_backend.outputs import PathTemporalHistory  # noqa: E402
from restir_lab.shell.camera import Camera  # noqa: E402
from restir_lab.shell.image import tonemap, write_png  # noqa: E402


ATLAS_DIR = Path(__file__).resolve().parent
PROOF_PATH = ATLAS_DIR / "content" / "proof_pixel.edn"
DOC_SOURCE_PATH = ROOT / "docs" / "architecture" / "atlas.edn"
DOC_OUTPUT_DIR = ROOT / "docs" / "architecture"
GENERATED_DIR = ATLAS_DIR / "generated"
SCHEMA = "restir-lab.atlas-fixture.v2"
DOC_SCHEMA = "restir-lab.architecture-doc.v1"
TIERS = ("orientation", "working-model", "proof-and-source")
GENERATED_NOTICE = "<!-- Generated by atlas/build.py from atlas.edn. Do not edit. -->"


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(f"architecture atlas: {message}")


def _form(value: Any, operator: str | None = None) -> tuple[str, str, dict, list]:
    _require(isinstance(value, list) and len(value) >= 3,
             "every form must be [operator id attributes ...]")
    op, form_id, attributes, *children = value
    _require(isinstance(op, str) and isinstance(form_id, str),
             "form operator and id must be strings")
    _require(isinstance(attributes, dict), f"{op} {form_id} attributes must be a map")
    if operator is not None:
        _require(op == operator, f"expected {operator}, got {op}")
    return op, form_id, attributes, children


def _validate_model(value: Any, context: str) -> None:
    if isinstance(value, list):
        _require(value, f"{context} model vectors cannot be empty")
        if not isinstance(value[0], str):
            _require(all(item is None or isinstance(item, str | bool | int | float)
                         for item in value),
                     f"{context} data vectors must contain scalar values")
        for child in value[1:]:
            _validate_model(child, context)
        return
    if isinstance(value, dict):
        _require(all(isinstance(key, str) for key in value),
                 f"{context} model map keys must be strings")
        for child in value.values():
            _validate_model(child, context)
        return
    _require(value is None or isinstance(value, str | bool | int | float),
             f"{context} model contains unsupported {type(value).__name__}")


def load_document() -> dict[str, Any]:
    """Validate and normalize the canonical documentation AST."""
    root = load_edn(DOC_SOURCE_PATH)
    op, atlas_id, metadata, children = _form(root, "defatlas")
    del op
    _require(metadata.get("schema_version") == 1, "schema_version must be 1")
    _require(metadata.get("tiers") == list(TIERS), "tier order is fixed")

    sources: dict[str, dict] = {}
    views: dict[str, dict] = {}
    chapter_forms: list[tuple[str, dict, list]] = []
    for child in children:
        child_op, child_id, attributes, grandchildren = _form(child)
        _require(child_op in {"source", "view", "chapter"},
                 f"unknown top-level form {child_op}")
        if child_op == "source":
            _require(not grandchildren, f"source {child_id} cannot have children")
            _require(child_id not in sources, f"duplicate source {child_id}")
            _require(all(isinstance(attributes.get(key), str)
                         for key in ("path", "symbol", "role")),
                     f"source {child_id} is incomplete")
            _require((ROOT / attributes["path"]).is_file(),
                     f"source {child_id} path does not exist")
            sources[child_id] = {"id": child_id, **attributes}
        elif child_op == "view":
            _require(not grandchildren, f"view {child_id} cannot have children")
            _require(child_id not in views, f"duplicate view {child_id}")
            _require(attributes.get("dimension") in {0, 1, 2, 3, 4},
                     f"view {child_id} has invalid dimension")
            _require(isinstance(attributes.get("alt"), str) and attributes["alt"],
                     f"view {child_id} needs alt text")
            nodes = attributes.get("nodes")
            edges = attributes.get("edges")
            _require(isinstance(nodes, list) and nodes, f"view {child_id} needs nodes")
            _require(isinstance(edges, list), f"view {child_id} needs edges")
            node_ids = [node.get("id") for node in nodes if isinstance(node, dict)]
            _require(len(node_ids) == len(nodes) == len(set(node_ids)),
                     f"view {child_id} node ids must be unique")
            for node in nodes:
                _require(all(key in node for key in ("label", "detail", "x", "y")),
                         f"view {child_id} has incomplete node")
            for edge in edges:
                _require(isinstance(edge, list) and len(edge) == 3,
                         f"view {child_id} edges are [from to label]")
                _require(edge[0] in node_ids and edge[1] in node_ids,
                         f"view {child_id} edge does not resolve")
            views[child_id] = {"id": child_id, **attributes}
        else:
            chapter_forms.append((child_id, attributes, grandchildren))

    chapters = []
    chapter_ids = set()
    for chapter_id, attributes, tier_forms in chapter_forms:
        _require(chapter_id not in chapter_ids, f"duplicate chapter {chapter_id}")
        chapter_ids.add(chapter_id)
        _require(attributes.get("view") in views,
                 f"chapter {chapter_id} view does not resolve")
        source_ids = attributes.get("sources")
        _require(isinstance(source_ids, list) and source_ids,
                 f"chapter {chapter_id} needs sources")
        _require(all(source_id in sources for source_id in source_ids),
                 f"chapter {chapter_id} source does not resolve")
        tiers = []
        for tier_form in tier_forms:
            tier_op, tier_id, tier, grandchildren = _form(tier_form, "tier")
            del tier_op
            _require(not grandchildren, f"tier {chapter_id}/{tier_id} cannot nest forms")
            required = ("label", "summary", "prose", "insights", "pitfalls", "model")
            _require(all(key in tier for key in required),
                     f"tier {chapter_id}/{tier_id} is incomplete")
            _require(isinstance(tier["prose"], list) and tier["prose"],
                     f"tier {chapter_id}/{tier_id} needs prose")
            _require(isinstance(tier["insights"], list) and tier["insights"],
                     f"tier {chapter_id}/{tier_id} needs insights")
            _require(isinstance(tier["pitfalls"], list) and tier["pitfalls"],
                     f"tier {chapter_id}/{tier_id} needs pitfalls")
            _validate_model(tier["model"], f"tier {chapter_id}/{tier_id}")
            tiers.append({"id": tier_id, **tier})
        _require(tuple(tier["id"] for tier in tiers) == TIERS,
                 f"chapter {chapter_id} must contain all tiers in order")
        chapters.append({"id": chapter_id, **attributes, "tiers": tiers})

    chapters.sort(key=lambda chapter: chapter["order"])
    _require([chapter["order"] for chapter in chapters]
             == list(range(1, len(chapters) + 1)),
             "chapter order must be contiguous")
    return {
        "schema": DOC_SCHEMA,
        "id": atlas_id,
        **metadata,
        "chapters": chapters,
        "views": views,
        "sources": sources,
        "denotation": root,
    }


def _json_value(value: Any) -> Any:
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, Enum):
        return {"name": value.name.lower(), "value": int(value.value)}
    if is_dataclass(value):
        return {
            field.name: _json_value(getattr(value, field.name))
            for field in fields(value)
            if field.init
        }
    if isinstance(value, Sequence) and not isinstance(value, str | bytes):
        return [_json_value(item) for item in value]
    if isinstance(value, Mapping):
        return {str(key): _json_value(item) for key, item in value.items()}
    if value is None or isinstance(value, str | bool | int | float):
        return value
    raise TypeError(f"cannot serialize atlas value {type(value).__name__}")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def _dsl_atom(value: Any) -> str:
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        if re.fullmatch(r"[A-Za-z][A-Za-z0-9+*/?!_.:/-]*", value):
            return value
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def _sexpr(value: Any, indent: int = 0) -> str:
    """Pretty-print a compact Clojure-like projection of an AST value."""
    if isinstance(value, dict):
        items = []
        for key, child in value.items():
            items.append(f":{key} {_sexpr(child, indent + 2)}")
        inline = "{" + " ".join(items) + "}"
        if len(inline) <= 92 and "\n" not in inline:
            return inline
        pad = " " * (indent + 2)
        return "{\n" + pad + ("\n" + pad).join(items) + "\n" + " " * indent + "}"
    if isinstance(value, list):
        if not value:
            return "[]"
        children = [_sexpr(child, indent + 2) for child in value]
        inline = "(" + " ".join(children) + ")"
        if len(inline) <= 92 and all("\n" not in child for child in children):
            return inline
        pad = " " * (indent + 2)
        return "(" + children[0] + "\n" + pad + ("\n" + pad).join(children[1:]) + ")"
    return _dsl_atom(value)


def _svg_for_view(view: dict[str, Any]) -> str:
    nodes = view["nodes"]
    timeline = view["projection"] == "timeline"
    node_width = 124 if timeline else 180
    node_height = 62
    node_by_id = {node["id"]: node for node in nodes}
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 350" role="img" '
        f'aria-labelledby="title desc">',
        f'<title id="title">{escape(view["title"])}</title>',
        f'<desc id="desc">{escape(view["alt"])}</desc>',
        '<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" '
        'orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#687672"/></marker></defs>',
        '<rect width="1000" height="350" rx="12" fill="#f4efe4"/>',
    ]
    for source_id, target_id, label in view["edges"]:
        source = node_by_id[source_id]
        target = node_by_id[target_id]
        sx = source["x"] + node_width
        sy = source["y"] + node_height / 2
        tx = target["x"]
        ty = target["y"] + node_height / 2
        bend = max(28, abs(tx - sx) * .42)
        if tx >= sx:
            path = f"M {sx} {sy} C {sx + bend} {sy}, {tx - bend} {ty}, {tx} {ty}"
        else:
            lower = max(sy, ty) + 72
            path = f"M {sx} {sy} C {sx + 36} {lower}, {tx - 36} {lower}, {tx} {ty}"
        parts.append(
            f'<path d="{path}" fill="none" stroke="#687672" stroke-width="1.7" '
            'marker-end="url(#arrow)"/>')
        if label:
            lx = (sx + tx) / 2
            ly = (sy + ty) / 2 - 7
            parts.append(
                f'<text x="{lx}" y="{ly}" text-anchor="middle" fill="#687672" '
                f'font-family="ui-monospace,monospace" font-size="10">{escape(label)}</text>')
    palette = ("#d97928", "#168da0", "#3c75aa", "#d02a91", "#64766f")
    for index, node in enumerate(nodes):
        color = "#d97928" if node["id"] == "m20" else palette[index % len(palette)]
        parts.extend([
            f'<g id="{escape(node["id"])}" transform="translate({node["x"]} {node["y"]})">',
            f'<rect width="{node_width}" height="{node_height}" rx="7" fill="#fffdf7" '
            f'stroke="{color}" stroke-width="2"/>',
            f'<rect width="5" height="{node_height}" rx="3" fill="{color}"/>',
            f'<text x="14" y="24" fill="#202827" font-family="system-ui,sans-serif" '
            f'font-size="13" font-weight="700">{escape(node["label"])}</text>',
            f'<text x="14" y="44" fill="#5a6864" font-family="system-ui,sans-serif" '
            f'font-size="10.5">{escape(node["detail"])}</text>',
            '</g>',
        ])
    parts.append(
        f'<text x="18" y="336" fill="#687672" font-family="ui-monospace,monospace" '
        f'font-size="11">{escape(str(view["dimension"]))}D domain → {escape(view["projection"])}</text>')
    parts.append('</svg>\n')
    return "\n".join(parts)


def _markdown_table(table: dict[str, Any]) -> list[str]:
    headers = table["headers"]
    rows = table["rows"]
    return [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


def _chapter_markdown(document: dict[str, Any], chapter: dict[str, Any]) -> str:
    view = document["views"][chapter["view"]]
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {chapter['title']}",
        "",
        f"> {chapter['subtitle']}",
        "",
        "[Architecture atlas](README.md) · "
        "[Interactive proof atlas](../../atlas/README.md) · "
        "[Roadmap](../../ROADMAP.md)",
        "",
        f"![{view['alt']}](assets/{view['id']}.svg)",
        "",
    ]
    for tier_number, tier in enumerate(chapter["tiers"], start=1):
        lines.extend([
            f"## Tier {tier_number} — {tier['label']}",
            "",
            f"**{tier['summary']}**",
            "",
        ])
        for paragraph in tier["prose"]:
            lines.extend([paragraph, ""])
        lines.extend(["### Compact architecture form", "", "```clojure",
                      _sexpr(tier["model"]), "```", "", "### Key insights", ""])
        lines.extend(f"- {item}" for item in tier["insights"])
        lines.extend(["", "### Common pitfalls", ""])
        lines.extend(f"- {item}" for item in tier["pitfalls"])
        lines.append("")
        if "table" in tier:
            lines.extend(_markdown_table(tier["table"]))
            lines.append("")
    lines.extend(["## Source trail", ""])
    for source_id in chapter["sources"]:
        source = document["sources"][source_id]
        lines.append(
            f"- [`{source['path']}`](../../{source['path']}) — "
            f"{source['symbol']}; {source['role']}.")
    lines.extend(["", "---", ""])
    chapters = document["chapters"]
    index = chapters.index(chapter)
    neighbors = []
    if index:
        previous = chapters[index - 1]
        neighbors.append(f"← [{previous['title']}]({previous['id']}.md)")
    if index + 1 < len(chapters):
        following = chapters[index + 1]
        neighbors.append(f"[{following['title']}]({following['id']}.md) →")
    lines.extend([" · ".join(neighbors), ""])
    return "\n".join(lines)


def _index_markdown(document: dict[str, Any]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {document['title']}",
        "",
        f"> {document['subtitle']}",
        "",
        "This is the static front door to the architecture. Each chapter repeats the same "
        "three depths, so you can skim the whole system or descend locally without changing "
        "vocabulary.",
        "",
        "For code-level contracts, state ownership, backend lowering, and change impact, "
        "continue into the [technical architecture design](../design/README.md).",
        "",
        "> **Current boundary:** M20 is active. ReSTIR PT correction/reduction remains "
        "host-orchestrated, and Slang PT reuse still shares the Taichi route. M21 graph "
        "composition is complete but does not close that native-backend gap.",
        "",
        "## Choose a chapter",
        "",
        "| Chapter | Question it answers | Projection |",
        "| --- | --- | --- |",
    ]
    questions = {
        "system": "How does the renderer lower from authored data to execution and inspection?",
        "domains": "Why are direct light samples and indirect paths separate?",
        "state": "How does reuse remain deterministic, immutable, and parallel?",
        "proof": "How can one pixel carry inspectable correctness evidence?",
        "retrospective": "What should be kept or changed on a restart?",
    }
    for chapter in document["chapters"]:
        view = document["views"][chapter["view"]]
        lines.append(
            f"| [{chapter['title']}]({chapter['id']}.md) | {questions[chapter['id']]} | "
            f"{view['dimension']}D → {view['projection']} |")
    lines.extend([
        "",
        "## The three tiers",
        "",
        "1. **Orientation** — the five-minute mental model, metaphors, and boundaries.",
        "2. **Working model** — contracts, state, data flow, and implementation consequences.",
        "3. **Proof and source** — equations, caveats, runtime evidence, tests, and code anchors.",
        "",
        "## Dimensional key",
        "",
        "| Domain | Representation | Use |",
        "| --- | --- | --- |",
        "| 0D | Concept, invariant, equation | Name one irreducible fact. |",
        "| 1D | Timeline, estimator ladder, chart | Explain order or accumulation. |",
        "| 2D | Layer, branch, ownership, or dependency map | Explain topology and boundaries. |",
        "| 3D | Orbitable path territory | Explain geometry and reconnection. |",
        "| 4D | Spatiotemporal lineage projected into maps and controls | Explain reuse across pixels and frames. |",
        "",
        "## Reading paths",
        "",
        "- **New to the project:** read Tier 1 in chapter order.",
        "- **Changing code:** read Tier 2 in the relevant chapter, then follow its source trail.",
        "- **Validating reuse math:** read Tier 3 of Sampling domains and Proof and introspection.",
        "- **Planning new work:** read System and lowering plus Retrospective and restart.",
        "",
        "## Interactive territory",
        "",
        "The [locally served atlas](../../atlas/README.md) consumes the same documentation "
        "AST and adds synchronized maps, charts, exact replay evidence, an orbitable path, "
        "and counterfactual WRS/Jacobian controls.",
        "",
        "`ROADMAP.md` remains the source of truth for project vision and milestone status. "
        "This atlas is its generated conceptual and evidentiary projection.",
        "",
    ])
    return "\n".join(lines)


def generate_docs(document: dict[str, Any], destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for markdown in destination.glob("*.md"):
        if markdown.read_text(encoding="utf-8").startswith(GENERATED_NOTICE):
            markdown.unlink()
    assets = destination / "assets"
    if assets.exists():
        shutil.rmtree(assets)
    assets.mkdir()
    (destination / "README.md").write_text(
        _index_markdown(document), encoding="utf-8")
    for chapter in document["chapters"]:
        (destination / f"{chapter['id']}.md").write_text(
            _chapter_markdown(document, chapter), encoding="utf-8")
        view = document["views"][chapter["view"]]
        (assets / f"{view['id']}.svg").write_text(
            _svg_for_view(view), encoding="utf-8")


def _camera(source: dict, resolution: int) -> Camera:
    authored = source["camera"]
    return Camera(
        authored["eye"], authored["look_at"], authored["up"],
        authored["fov"], resolution, resolution)


def _stable_plan_projection(graph, plan):
    """Return one stable valid order for documentation serialization.

    ``compile_pipeline`` permits independent ready nodes to appear in either
    order because runtime semantics do not depend on that choice. The atlas
    needs byte-stable output across Python hash seeds, so it projects the same
    dependency DAG with authored-node order as the deterministic tie-breaker.
    """
    authored_order = {node.node_id: index for index, node in enumerate(graph.nodes)}
    by_id = {step.node.node_id: step for step in plan.steps}
    dependencies: dict[str, set[str]] = {}
    children: dict[str, set[str]] = {node_id: set() for node_id in by_id}
    for node_id, step in by_id.items():
        required = {
            ref.node for name, ref in step.inputs.items()
            if name not in step.definition.delayed_inputs and ref.node in by_id
        }
        dependencies[node_id] = required
        for parent in required:
            children[parent].add(node_id)
    ready = sorted(
        (node_id for node_id, required in dependencies.items() if not required),
        key=authored_order.__getitem__)
    ordered = []
    while ready:
        node_id = ready.pop(0)
        ordered.append(by_id[node_id])
        for child in sorted(children[node_id], key=authored_order.__getitem__):
            dependencies[child].discard(node_id)
            if not dependencies[child] and by_id[child] not in ordered:
                if child not in ready:
                    ready.append(child)
    if len(ordered) != len(plan.steps):
        raise RuntimeError("atlas could not canonicalize compiled pipeline")
    return tuple(ordered)


def _pipeline_payload(integrator: IntegratorConfig, replay) -> dict[str, Any]:
    graph = pipeline_from_integrator(
        integrator, graph_id="atlas/proof-pixel",
        title="Proof-pixel ReSTIR PT")
    plan = compile_pipeline(
        graph, builtin_operator_catalog(), backend="scalar",
        terminals=("frame", "radiance", "beauty"))
    projected = pipeline_replay(graph, replay)
    stable_steps = _stable_plan_projection(graph, plan)
    groups = []
    transport_nodes = tuple(
        step.node.node_id for step in stable_steps
        if step.definition.category in ("Direct", "Indirect"))
    stable_groups = []
    for step in stable_steps:
        if step.definition.category in ("Direct", "Indirect"):
            continue
        if step.definition.operator_id == "render.standard_frame":
            stable_groups.append((*transport_nodes, step.node.node_id))
        else:
            stable_groups.append((step.node.node_id,))
    for index, nodes in enumerate(stable_groups):
        groups.append({"id": f"dispatch-{index}", "nodes": list(nodes)})

    step_index = {
        step.node.node_id: index for index, step in enumerate(stable_steps)}
    consumers = {}
    for index, step in enumerate(stable_steps):
        for input_name, ref in step.inputs.items():
            if input_name not in step.definition.delayed_inputs:
                consumers.setdefault((ref.node, ref.port), []).append(index)
    terminals = {
        (ref.node, ref.port) for ref in plan.terminal_refs.values()}
    resources = []
    for step in stable_steps:
        first = step_index[step.node.node_id]
        for port, spec in step.definition.outputs.items():
            key = (step.node.node_id, port)
            resources.append({
                "node": key[0], "port": key[1], "first_step": first,
                "last_step": max(consumers.get(key, (first,))),
                "retained": key in terminals, "kind": spec.kind,
            })
    return {
        "authored": graph.to_dict(),
        "semantic_hash": graph.semantic_hash,
        "compiled": {
            "backend": plan.backend,
            "terminals": list(plan.terminals),
            "steps": [{
                "node": step.node.node_id,
                "operator": step.definition.operator_id,
                "category": step.definition.category,
                "parameters": _json_value(step.parameters),
            } for step in stable_steps],
            "fused_groups": groups,
            "resources": resources,
            "delayed_nodes": list(plan.delayed_nodes),
        },
        "record_projection": [{
            "node": item.node_id,
            "operator": item.operator_id,
            "sample": item.sample_index,
            "payload_type": type(item.payload).__name__,
        } for item in projected.operators],
    }


def _entities(document: dict[str, Any], sample) -> dict[str, Any]:
    entities: dict[str, Any] = {}
    for chapter in document["chapters"]:
        entities[f"chapter:{chapter['id']}"] = {
            "kind": "chapter", "chapter": chapter["id"],
            "tier": "orientation", "label": chapter["title"],
        }
        for tier in chapter["tiers"]:
            entities[f"tier:{chapter['id']}:{tier['id']}"] = {
                "kind": "tier", "chapter": chapter["id"],
                "tier": tier["id"], "label": tier["label"],
            }
    for index, vertex in enumerate(sample.indirect.vertices):
        entities[f"vertex:{index}"] = {
            "kind": "path-vertex", "chapter": "proof",
            "tier": "working-model", "stage": "fresh",
            "label": f"Path vertex {vertex.depth}", "record_index": index,
        }
    for index, contribution in enumerate(sample.indirect.contributions):
        entities[f"contribution:{index}"] = {
            "kind": "path-contribution", "chapter": "proof",
            "tier": "working-model", "stage": "fresh",
            "label": f"Contribution {contribution.contribution_index}",
            "record_index": index,
        }
    for index, _update in enumerate(sample.fresh_path_reservoir):
        entities[f"fresh:{index}"] = {
            "kind": "reservoir-update", "chapter": "proof",
            "tier": "working-model", "stage": "fresh",
            "label": f"Fresh update {index + 1}", "record_index": index,
        }
    for index, _shift in enumerate(sample.temporal_shifts):
        entities[f"temporal:{index}"] = {
            "kind": "temporal-shift", "chapter": "proof",
            "tier": "proof-and-source", "stage": "temporal",
            "label": "Temporal shift", "record_index": index,
        }
    for index, shift in enumerate(sample.spatial_shifts):
        entities[f"spatial:{index}"] = {
            "kind": "spatial-shift", "chapter": "proof",
            "tier": "proof-and-source", "stage": "spatial",
            "label": f"Spatial attempt {index}", "record_index": index,
            "status": "valid" if shift.valid else "failed",
        }
    entities["final:reservoir"] = {
        "kind": "final-reservoir", "chapter": "proof",
        "tier": "proof-and-source", "stage": "evaluate",
        "label": "Final path reservoir", "record_index": 0,
    }
    return entities


def _validate_canonical(replay, expected: dict[str, Any]) -> None:
    if len(replay.samples) != 1:
        raise RuntimeError("atlas fixture must contain exactly one sample")
    sample = replay.samples[0]
    if sample.indirect is None:
        raise RuntimeError("atlas fixture lost its indirect trace")
    actual_shape = {
        "vertices": 6,
        "contributions": 5,
        "fresh_updates": 5,
        "temporal": 1,
        "spatial": 6,
        "valid_spatial": 3,
        "failed_spatial": 3,
        "accepted_spatial": 2,
    }
    actual = {
        "vertices": len(sample.indirect.vertices),
        "contributions": len(sample.indirect.contributions),
        "fresh_updates": len(sample.fresh_path_reservoir),
        "temporal": len(sample.temporal_shifts),
        "spatial": len(sample.spatial_shifts),
        "valid_spatial": sum(item.valid for item in sample.spatial_shifts),
        "failed_spatial": sum(not item.valid for item in sample.spatial_shifts),
        "accepted_spatial": sum(item.accepted for item in sample.spatial_shifts),
    }
    authored_shape = {key: expected[key] for key in actual_shape}
    if actual != authored_shape:
        raise RuntimeError(
            f"canonical atlas pixel changed: expected {authored_shape}, got {actual}")
    temporal = sample.temporal_shifts[0]
    if (not temporal.valid or not temporal.accepted
            or temporal.hybrid_shift is None
            or temporal.hybrid_shift.mapping.name.lower()
            != expected["temporal_mapping"]):
        raise RuntimeError("canonical temporal hybrid reconnection changed")
    if not sample.final_path_reservoir:
        raise RuntimeError("canonical final path reservoir disappeared")
    final = sample.final_path_reservoir[-1]
    if (final.M != expected["final_M"] or final.selected_temporal_shift is None
            or final.selected_spatial_shift is None):
        raise RuntimeError("canonical final reservoir lineage changed")


def generate(destination: Path, docs_destination: Path | None = None) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    document = load_document()
    proof = load_edn(PROOF_PATH)
    if proof.get("schema_version") != 1:
        raise RuntimeError("proof-pixel schema_version must be 1")
    resolution = proof["resolution"]
    source = scene_dict(proof["scene"])
    scene = lower_scene(source)
    camera = _camera(source, resolution)
    path_config = proof["integrator"]
    if path_config.get("mode") != "restir_pt":
        raise RuntimeError("proof-pixel integrator must be restir_pt")
    integrator = IntegratorConfig(
        indirect=PathEstimatorConfig.restir_pt(
            max_depth=path_config["max_depth"],
            temporal_m_cap=path_config["temporal_m_cap"],
            spatial_mode=path_config["spatial_mode"],
            spatial_neighbors=path_config["spatial_neighbors"],
            spatial_radius=path_config["spatial_radius"]))

    frame4 = scalar.render_frame(
        scene, camera, 1, frame=proof["source_frame"], integrator=integrator)
    history = PathTemporalHistory.capture(scene, camera, frame4)
    frame5 = scalar.render_frame(
        scene, camera, 1, frame=proof["target_frame"], integrator=integrator,
        path_temporal_history=history)
    x, y = proof["pixel"]
    replay = replay_pixel(
        scene, camera,
        PixelSelection(x, y, proof["target_frame"], 1, integrator=integrator),
        path_temporal_history=history,
        path_spatial_source=frame5.path_spatial_source)
    _validate_canonical(replay, proof["expected"])
    sample = replay.samples[0]

    source_image = f"frame-{proof['source_frame']}.png"
    target_image = f"frame-{proof['target_frame']}.png"
    write_png(str(destination / source_image),
              tonemap(frame4.radiance, proof["exposure"]))
    write_png(str(destination / target_image),
              tonemap(frame5.radiance, proof["exposure"]))
    bounds = debug_bounds(scene, camera)

    payload = {
        "schema": SCHEMA,
        "document": document,
        "metadata": {
            "fixture": proof["fixture_id"],
            "scene": proof["scene"],
            "resolution": [resolution, resolution],
            "source_frame": proof["source_frame"],
            "target_frame": proof["target_frame"],
            "pixel": proof["pixel"],
            "sample": proof["sample"],
            "backend": "scalar",
            "policy": "exact/unbiased",
            "integrator": _json_value(integrator),
        },
        "entities": _entities(document, sample),
        "scene": {
            "authored": source,
            "wireframe": scene_wireframe(scene, camera).tolist(),
            "bounds": {"center": bounds.center.tolist(),
                       "radius": bounds.radius},
            "image_plane": image_plane(camera, bounds).tolist(),
        },
        "frames": {
            "source": {"frame": proof["source_frame"],
                       "image": f"generated/{source_image}"},
            "target": {"frame": proof["target_frame"],
                       "image": f"generated/{target_image}"},
        },
        "pipeline": _pipeline_payload(integrator, replay),
        "replay": _json_value(replay),
        "summary": {
            "path_vertices": len(sample.indirect.vertices),
            "contributions": len(sample.indirect.contributions),
            "fresh_updates": len(sample.fresh_path_reservoir),
            "temporal_attempts": len(sample.temporal_shifts),
            "spatial_attempts": len(sample.spatial_shifts),
            "valid_spatial": sum(item.valid for item in sample.spatial_shifts),
            "failed_spatial": sum(not item.valid for item in sample.spatial_shifts),
            "accepted_spatial": sum(item.accepted for item in sample.spatial_shifts),
            "final_M": sample.final_path_reservoir[-1].M,
            "final_W": sample.final_path_reservoir[-1].W,
            "sample_radiance": sample.sample_radiance.tolist(),
        },
    }
    data_path = destination / "atlas-v2.json"
    data_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8")
    generated_names = ("atlas-v2.json", source_image, target_image)
    manifest = {
        "schema": SCHEMA,
        "files": {
            name: _sha256(destination / name)
            for name in generated_names
        },
    }
    (destination / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8")
    if docs_destination is not None:
        generate_docs(document, docs_destination)


def _relative_files(root: Path) -> list[Path]:
    return sorted(path.relative_to(root) for path in root.rglob("*") if path.is_file())


def check() -> None:
    with tempfile.TemporaryDirectory(prefix="restir-atlas-") as temporary:
        root = Path(temporary)
        target = root / "atlas"
        docs_target = root / "docs"
        generate(target, docs_target)
        expected = _relative_files(target)
        actual = (_relative_files(GENERATED_DIR)
                  if GENERATED_DIR.exists() else [])
        if actual != expected:
            raise SystemExit(
                f"generated atlas file set drifted: expected {expected}, got {actual}")
        drifted = [str(name) for name in expected
                   if (target / name).read_bytes()
                   != (GENERATED_DIR / name).read_bytes()]
        if drifted:
            raise SystemExit(
                "generated atlas artifacts drifted: " + ", ".join(drifted))
        expected_docs = _relative_files(docs_target)
        actual_docs = sorted(
            path.relative_to(DOC_OUTPUT_DIR)
            for path in DOC_OUTPUT_DIR.rglob("*")
            if path.is_file() and path != DOC_SOURCE_PATH)
        if actual_docs != expected_docs:
            raise SystemExit(
                f"generated docs file set drifted: expected {expected_docs}, got {actual_docs}")
        drifted_docs = [str(name) for name in expected_docs
                        if (docs_target / name).read_bytes()
                        != (DOC_OUTPUT_DIR / name).read_bytes()]
        if drifted_docs:
            raise SystemExit(
                "generated docs artifacts drifted: " + ", ".join(drifted_docs))


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="regenerate in a temporary directory and fail on drift")
    args = parser.parse_args(argv)
    if args.check:
        check()
        print("atlas generated artifacts are current")
        return
    if GENERATED_DIR.exists():
        shutil.rmtree(GENERATED_DIR)
    generate(GENERATED_DIR, DOC_OUTPUT_DIR)
    print(
        f"wrote atlas artifacts to {GENERATED_DIR.relative_to(ROOT)} "
        f"and documentation to {DOC_OUTPUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
