# Site Settings
title: "Topos Of Noether"
description: "This my digital idea scratchbook, full of speculation and experiments and meandering thoughts."

# URL Settings (Crucial for proper links and formatting)
url: "https://ikrima.github.io" # Your main domain or custom domain
baseurl: "/topos.noether"       # Subpath of your site (leave as "" if using username.github.io repo)

# Theme Selection
theme: jekyll-theme-architect     # Use a GitHub-supported theme like jekyll-theme-tactile or jekyll-theme-minima
# remote_theme: username/theme    # Alternative: Use any open-source theme from GitHub

# Build Settings & Formatters
markdown: kramdown
highlighter: rouge
# permalink: /:title/

# Directory Controls
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
