# Theme Selection
theme: jekyll-theme-architect     # Use a GitHub-supported theme like jekyll-theme-tactile or jekyll-theme-minima

# Site Settings
title: "Topos Of Noether"
description: "This my digital idea scratchbook, full of speculation and experiments and meandering thoughts."

# Build Settings & Formatters
markdown: kramdown
highlighter: rouge
# permalink: /:title/

# # URL Settings (Crucial for proper links and formatting)
# url: "https://ikrima.github.io" # Your main domain or custom domain
# baseurl: "/topos.noether"       # Subpath of your site (leave as "" if using username.github.io repo)
#
# # Directory Controls
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/
